variables:
  THREADS: 9
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - ./cache.nar

before_script:
  - |
    if [ -e ./cache.nar ]; then
        nix-store --import < ./cache.nar
    fi

    nix-env -iA git -f '<nixpkgs>'
    nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/db557aab7b690f5e0e3348459f2e4dc8fd0d9298

    mkdir -p $HOME/.config/nix
    cat > $HOME/.config/nix/nix.conf <<EOF
    substituters = https://cache.nixos.org https://trec-car-tools.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= trec-car-tools.cachix.org-1:zlHkXRIQit3P6UdWD/tC7rHI4OmorVE/e2d9HcE80dQ=
    EOF

    mkdir -p $HOME/.config/cachix
    cat > $HOME/.config/cachix/config.dhall <<EOF
    { authToken = $CACHIX_AUTH_TOKEN
    , binaryCaches =
        [ { name = "trec-car-tools"
          , secretKey = $CACHIX_SECRET_KEY
          }
        ] : List { name : Text, secretKey : Text }
    }
    EOF

nix-build:
  image: nixos/nix
  script:
    - nix-build . -A env --cores 1 -j $THREADS | cachix push trec-car-tools
    - nix-store --export $(nix-store -qR ./result) > ./cache.nar

static-dist:
  image: registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-alpine
  before_script:
    - ghc --version
  script:
    - sudo apk add xz xz-dev icu icu-dev icu-static zlib-static
    - cabal update
    - |
      cabal --store-dir=$(pwd)/.cabal-store \
        v2-install \
        --disable-shared --enable-static --enable-executable-static \
        -fstatic --ghc-options='-optl=-static' \
        --installdir=out --overwrite-policy=always \
        rank-lips
  cache:
    paths:
      - .cabal-store
  artifacts:
    expire_in: 8 weeks
    paths:
      - out
